# Show training sample
rule visualiseTrainingData:
    input:
        script = "visualiseTrainingData.py",
        data_dir = "../../data/structures/simulations/Label"
    output:
        out_dir = directory("../../results/train_data")
    shell:
        """
        python ./visualiseTrainingData.py
    """

# Compare the predictions from differemt models
rule visualisePredictionsPureOnlyBoth:
        input:
                script = "visualisePredictionsPureOnlyBoth.py",
                expImage = "../../data/expPNG",
                predictions = "../../data/structures/predictions"
        output:
                output = directory("../../results/predictionsPureOnlyBoth")
        shell:
                """
                ./visualisePredictionsPureOnlyBoth.py
                """

# Theoretical local distributions
rule calTheoreDistributions:
    input:
        script = "calTheoreDistributions.py",
        data_dir = "../../data/structures/simulations/"
    output:
        out_dir = directory("../../results/theoretical_distributions/"),
        processed_dir = directory("../../processed_data/theory_distributions/")
    shell:
        """
        ./calTheoreDistributions.py
        """

# Calculate the distributions for predicted configurations for different models
rule calDistributions:
    input:
        script = "calDistributions.py",
        tool = "water.py",
        data_dir = "../../data/structures/predictions"
    output:
        out_dir = directory("../../processed_data/structure_properties")
    shell:
        """
        ./calDistributions.py
        """

# Calculate the distribution distances between prediction and theory
rule calDistances:
    input:
        script = "calDistances.py",
        theory = "../../processed_data/theory_distributions",
        data_dir = "../../processed_data/structure_properties"
    output:
        out_dir = directory("../../processed_data/distribution_distances")
    shell:
        """
        ./calDistances.py
        """

# Visualise model performance individually
rule visualiseRadar:
        input:
                "visualiseRadar.py",
                 "../../processed_data/distribution_distances/similarities_Label_All.json",
                 "../../processed_data/distribution_distances/similarities_Label_Top.json",
        output:
                out_dir = directory("../../results/radar")
        shell:
                """
                ./visualiseRadar.py
                """
# Visualise mean performance for the same hyperparameter
rule visualiseEvaluateMeanInRadar:
        input:
                "visualiseRadar.py",
                 "../../processed_data/distribution_distances/similarities_Label_All.json",
                 "../../processed_data/distribution_distances/similarities_Label_Top.json",
        output:
                out_dir = directory("../../results/meanInRadar")
        shell:
                """
                ./visualiseEvaluateMeanInRadar.py
                """

# Visualise distribution comparisons 
rule visualiseDistributionCompare:
        input:
                script = "visualiseDistributionCompare.py",
                processed_dir = "../../processed_data/theory_distributions/",
                similarity_json = "../../processed_data/distribution_distances/similarities_Label_Top.json",
                npz_P_and_models_dir ="../../processed_data/structure_properties/P/",
                npz_All_and_Top_dir = "../../processed_data/theory_distributions/Label/"

        output:
                out_dir = directory("../../results/compare_distributions/")
        shell:
                """
                ./visualiseDistributionCompare.py
                """
