# Show training sample
rule visualiseTrainingData:
    input:
        script = "visualiseTrainingData.py",
        data_dir = "../../data/structures/simulations/Label"
    output:
        out_dir = directory("../../results/train_data")
    shell:
        """
        python ./visualiseTrainingData.py
    """

# Compare the predictions from differemt models
rule visualisePredictionsPureOnlyBoth:
        input:
                script = "visualisePredictionsPureOnlyBoth.py",
                expImage = "../../data/expPNG",
                predictions = "../../data/structures/predictions"
        output:
                output = directory("../../results/predictionsPureOnlyBoth")
        shell:
                """
                ./visualisePredictionsPureOnlyBoth.py
                """

# Theoretical local distributions
rule calTheoreDistributions:
    input:
        script = "calTheoreDistributions.py",
        data_dir = "../../data/structures/simulations/"
    output:
        out_dir = directory("../../results/theoretical_distributions/"),
        processed_dir = directory("../../processed_data/theory_distributions/")
    shell:
        """
        ./calTheoreDistributions.py
        """
